name: timbu_peek
description: "A Product Catalogue just for you"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  http: ^1.2.1
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#040944" # Deep blue background
  image: assets/shopping_cart.png
  android: true
  ios: true
  web: true
  fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/shopping_cart.png
